# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      containers:
        - name: app-teste
          image: gcr.io/dev-default-382019/app-teste:v12
          ports:
            - name: nginx
              containerPort: 80
            - name: app
              containerPort: 5000
